### ISSUE TITLE
hw2: general advantage estimation

### ISSUE THREAD

**Issue by cometta** [xuanlinli17/CS285_Fa19_Deep_Reinforcement_Learning#8]
@xuanlinli17 

Can share where did you get below formula from 

mb_advs[t] = delta + self.gamma * self.lam * mb_advs[t+1]  ?

https://github.com/xuanlinli17/CS285_Fa19_Deep_Reinforcement_Learning/blob/ba2e8e18c60b3a074f735d045b40f04a20efffca/hw2/cs285/agents/pg_agent.py#L86

**Comment by xuanlinli17** [comment]
This is the generalized advantage estimation (GAE).

https://github.com/openai/baselines/blob/master/baselines/ppo2/runner.py

**Comment by cometta** [comment]
Any reference i can read on return is equal to q value ?

https://github.com/xuanlinli17/CS285_Fa19_Deep_Reinforcement_Learning/blob/ba2e8e18c60b3a074f735d045b40f04a20efffca/hw2/cs285/agents/pg_agent.py#L88

Also, advantage should be mb_advs - values  ? 

https://github.com/xuanlinli17/CS285_Fa19_Deep_Reinforcement_Learning/blob/ba2e8e18c60b3a074f735d045b40f04a20efffca/hw2/cs285/agents/pg_agent.py#L89

**Comment by xuanlinli17** [comment]
```        
if not self.use_gae:
    # step 1: calculate q values of each (s_t, a_t) point, 
    # using rewards from that full rollout of length T: (r_0, ..., r_t, ..., r_{T-1})
    q_values = self.calculate_q_vals(rews_list)

    # step 2: calculate advantages that correspond to each (s_t, a_t) point
    advantage_values = self.estimate_advantage(obs, q_values)
```

<s>These two lines correspond to these two steps, respectively. `q_values` is unnormalized reward, while `advantage_values` is the normalized advantage.</s>

These two lines correspond to these two steps.

Sorry about this confusion. I believe when I implemented GAE, contrary to the implementation without GAE, the baseline prediction network (value network) estimated the raw advantage instead of the normalized advantage. Note that `q_values` refers to the raw `q_values` and I used a similar implementation to https://github.com/openai/baselines/blob/master/baselines/ppo2/runner.py (side note: in Openai Baselines, the reward is always normalized before calculating advantage, but the implementation should be the same whether the reward is normalized or not). In my GAE, advantage values are not normalized, and the raw advantage value is returned.
